### PR TITLE
Features/fixing geoid elevation provider

### PR DESCRIPTION
**Pull request by JakubBorekRainlabs**
Description in comments

### CODE REVIEW

**Comment by JakubBorekRainlabs** [comment]
1. Srtm gives terrain elevation relative to the egm96 geoid, not wgs84 ellipsoid.

I don't really understand what has happened here: we want terrain over wgs84, so if that was true then no geoid height calculations would be necessary

**Comment by JakubBorekRainlabs** [comment]
2. There was a bug in the geoid elevation provider, we accessed wrong data

**Comment by JakubBorekRainlabs** [comment]
3. There was a bug in the geoid height interpolation. I'm not sure if it could work the intended way so I made the bicubic interpolation normalized to 0..1 grid. That also makes things much simpler

**Comment by JakubBorekRainlabs** [comment]
4. I'm unsure if the bicubic interpolation is implemented correctly. It works well for planes, but I think the results for more complicated shapes are wrong, I may be wrong though.

The thing is that such a fancy interpolation is pretty much pointless in our applications. The difference compared to no interpolation is under 1m.

So I've added PgmElevationProviderNaive, that does not use any interpolation, just returns the corresponding cell height. If we find problems with the interpolating provider, we can safely fallback to it

**Comment by JakubBorekRainlabs** [comment]
It fails to build as TC configuration uses VS2013 and I've used c# 6 features. I'd like to update the VS, if that's not a problem :)

**Comment by kwesolowski** [comment]
Yes, please adjust to VS 2015

**Comment by JakubBorekRainlabs** [comment]
Done, builds now

> Yes, please adjust to VS 2015

**Pull request merged**
